<?php
payment_complete( string $transaction_id = '' );get_formatted_order_total( string $tax_display = '', boolean $display_refunded = true );set_status( string $new_status, string $note = '', boolean $manual_update = false );	maybe_set_date_paid( );maybe_set_date_completed( );update_status( $new_status, $note = '', $manual = false );status_transition( );get_data( );get_changes( );get_order_number( );get_order_key( string $context = 'view' );get_customer_id( string $context = 'view' );get_user_id( string $context = 'view' );get_user( );get_address_prop( string $prop, string $address = 'billing', string $context = 'view' );get_billing_first_name( string $context = 'view' );get_billing_last_name( string $context = 'view' );get_billing_company( string $context = 'view' );get_billing_address_1( string $context = 'view' );get_billing_address_2( string $context = 'view' );get_billing_city( string $context = 'view' );get_billing_state( string $context = 'view' );get_billing_postcode( string $context = 'view' );get_billing_country( string $context = 'view' );get_billing_email( string $context = 'view' );get_billing_phone( string $context = 'view' );get_shipping_first_name( string $context = 'view' );get_shipping_last_name( string $context = 'view' );get_shipping_company( string $context = 'view' );get_shipping_address_1( string $context = 'view' );get_shipping_address_2( string $context = 'view' );get_shipping_city( string $context = 'view' );get_shipping_state( string $context = 'view' );get_shipping_postcode( string $context = 'view' );get_shipping_country( string $context = 'view' );get_payment_method( string $context = 'view' );get_payment_method_title( string $context = 'view' );get_transaction_id( string $context = 'view' );get_customer_ip_address( string $context = 'view' );get_customer_user_agent( string $context = 'view' );get_created_via( string $context = 'view' );get_customer_note( string $context = 'view' );get_date_completed( string $context = 'view' );get_date_paid( string $context = 'view' );get_cart_hash( string $context = 'view' );get_address( string $type = 'billing' );get_shipping_address_map_url( );get_formatted_billing_full_name( );get_formatted_shipping_full_name( );get_formatted_billing_address( );get_formatted_shipping_address( );key_is_valid( mixed $key );	has_cart_hash( $cart_hash = '' );is_editable( );is_paid( );get_checkout_payment_url( boolean $on_checkout = false );	get_checkout_order_received_url( );get_cancel_order_url( string $redirect = '' );get_cancel_order_url_raw( string $redirect = '' );	get_cancel_endpoint( );	get_view_order_url( );add_order_note( string $note, integer $is_customer_note = 0, boolean $added_by_user = false );get_customer_order_notes( );get_refunds( );get_total_refunded( );	get_total_tax_refunded( );	get_total_shipping_refunded( );get_item_count_refunded( string $item_type = '' );	get_total_qty_refunded( string $item_type = 'line_item' );	get_qty_refunded_for_item( integer $item_id, string $item_type = 'line_item' );	get_total_refunded_for_item( integer $item_id, string $item_type = 'line_item' );	get_tax_refunded_for_item( integer $item_id, integer $tax_id, string $item_type = 'line_item' );	get_remaining_refund_amount( );	get_remaining_refund_items( );	add_order_item_totals_refund_rows( array & $total_rows, string $tax_display );	get_order_item_totals( mixed $tax_display = '' );	

//________________________________________________________________________________________________
//SETTERS : Peu de chances de les utiliser pour ce projet
set_address_prop( string $prop, string $address, mixed $value );
set_order_key( string $value );
set_customer_id( integer $value );
set_billing_first_name( string $value );
set_billing_last_name( string $value );
set_billing_company( string $value );
set_billing_address_1( string $value );
set_billing_address_2( string $value );
set_billing_city( string $value );
set_billing_state( string $value );
set_billing_postcode( string $value );
set_billing_country( string $value );
maybe_set_user_billing_email( );
set_billing_email( string $value );
set_billing_phone( string $value );
set_shipping_first_name( string $value );
set_shipping_last_name( string $value );
set_shipping_company( string $value );
set_shipping_address_1( string $value );
set_shipping_address_2( string $value );
set_shipping_city( string $value );
set_shipping_state( string $value );
set_shipping_postcode( string $value );
set_shipping_country( string $value );	
set_payment_method( string $payment_method = '' );
set_payment_method_title( string $value );
set_transaction_id( string $value );
set_customer_ip_address( string $value );
set_customer_user_agent( string $value );
set_created_via( string $value );	
set_customer_note( string $value );
set_date_completed( string|integer|null $date = null );
set_date_paid( string|integer|null $date = null );
set_cart_hash( string $value );